source 'https://github.com/noughts/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'NNZoomableImageView', :exclusive => true do
  pod "NNZoomableImageView", :path => "../"
  pod "NBULog"
end

target 'Tests', :exclusive => true do
  pod "NNZoomableImageView", :path => "../"
end
